# Generated by Django 4.1 on 2023-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': 'Access'},
        ),
        migrations.AddField(
            model_name='access',
            name='add',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='access',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
