# Generated by Django 4.1 on 2023-04-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_access_options_access_add_access_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=True)),
                ('change', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.access')),
            ],
        ),
    ]
