# Generated by Django 4.1 on 2023-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accessfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessfield',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
