# Generated by Django 4.1 on 2023-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_accessfield_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='add',
            new_name='can_add',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='delete',
            new_name='can_delete',
        ),
        migrations.RenameField(
            model_name='accessfield',
            old_name='change',
            new_name='can_change',
        ),
        migrations.RenameField(
            model_name='accessfield',
            old_name='view',
            new_name='can_view',
        ),
    ]
