# Generated by Django 4.1 on 2023-04-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_add_access_can_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
