# Generated by Django 4.1 on 2023-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('parent_company', 'Parent Company'), ('subsidiary', 'Subsidiary')], default='subsidiary', max_length=15)),
                ('status', models.CharField(choices=[('inactive', 'In-active'), ('active', 'Active')], default='inactive', max_length=8)),
            ],
        ),
    ]
