# Generated by Django 4.1 on 2023-04-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorType',
        ),
    ]
